---
- hosts: workstation
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install some pkgs
      yum: 
        name: ['git','httpd','vim']
        state: installed
      when:
        ansible_distribution=='centOS'


   
